name: Reflowster
titletagline: The hobbyists reflow soldering oven
markdown: redcarpet
kickstarterurl: https://www.kickstarter.com/projects/reflowster/reflowster-soldering-controller-for-surface-mount
highlighter: pygments
exclude: [tasks, misc_unused, README.md]
include: [.htaccess]
url: http://reflowster.com
#gems: [jekyll-navigation] #commented out because i modified jekyll navigation
gems: [jekyll-sitemap]
excerpt_separator: <!--more-->
authors:
  julian:
    display_name: Julian Hartline
    gravatar: 300aa4fabf894a18d740058bbcad03e6
    email: julianh2o@gmail.com
    web: http://www.julianhartline.com/
    twitter: reflowster
    github: julianh2o
