name: Reflowster
titletagline: The hobbyists reflow soldering oven
markdown: redcarpet
kickstarterurl: https://www.kickstarter.com/projects/reflowster/reflowster-soldering-controller-for-surface-mount
pygments: true
exclude: [tasks, misc_unused]
include: [.htaccess]
#gems: [jekyll-navigation]
excerpt_separator: <!--more-->
authors:
  julian:
    display_name: Julian Hartline
    gravatar: 300aa4fabf894a18d740058bbcad03e6
    email: julianh2o@gmail.com
    web: http://www.julianhartline.com/
    twitter: reflowster
    github: julianh2o
