#!/usr/bin/env bash
jekyll build && chmod -R a+r _site/ && rsync -apvvz --delete _site/ reflowst@reflowster.com:~/public_html/
ssh -t reflowst@reflowster.com 'chmod -R o-w /home/reflowst/public_html/; chmod -R g-w /home/reflowst/public_html/'
